### ISSUE TITLE
pmemcheck appears to ignore some pmem stores

### ISSUE THREAD

**Issue by GBuella** [pmem/valgrind#44] opened 2017-03-06 17:08 UTC
The following branch can used to reproduce an issue, which seems to be an issue with pmemcheck:
https://github.com/GBuella/pmemfile/tree/pmemcheck_trouble

See tha latest commit in the branch for details.
Run the tests of the repository to reproduce.

**Comment by tomaszkapela** [comment] 2017-03-14 13:08
I tried to reproduce this issue, but as we say it in Poland *u mnie działa*. Pmemcheck proprely reports the out of transaction stores in the test *rw.sparse_files*. As far as I can tell this is not a bug. Please verify this again and close this issue or provide more info on how to reproduce this.

**Comment by tomaszkapela** [comment] 2017-05-15 15:19
@GBuella can we close this?

**Comment by GBuella** [comment] 2017-05-15 15:25
http://www.theblaze.com/wp-content/uploads/2012/01/obama-yes-we-can_04-nov-08.jpg

**Closed as completed** 2017-05-15 15:26 UTC
